version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    volumes:
      - ./kibana/config:/usr/share/kibana/config
    ports:
      - "5600:5600"
    networks:
      - elastic

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.2
    volumes:
      #- ./filebeat/config:/usr/share/filebeat
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/parser_log.log:/parser.log
      - ./filebeat/mynewjson.json:/mynewjson.json
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - elastic


networks:
  elastic:
    driver: bridge
